# Generated by Django 5.2.1 on 2025-05-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('clarity_improvements', models.TextField(blank=True, null=True)),
                ('modern_adaptations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('recommended_refinements', models.TextField(blank=True, null=True)),
                ('standard_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='standards_analysis.standardanalysis')),
            ],
        ),
    ]
